import {
  Injectable,
  NotFoundException,
  ForbiddenException,
  BadRequestException,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateInvoiceDto } from './dto/create-invoice.dto';
import {
  InvoiceStatus,
  LeaseStatus,
  PaymentFrequency,
} from '@prisma/client';
import { addDays, addWeeks, addMonths, addYears } from 'date-fns';

@Injectable()
export class InvoiceService {
  constructor(private readonly prisma: PrismaService) {}

  async create(dto: CreateInvoiceDto) {
    const lease = await this.prisma.lease.findUnique({
      where: {
        id: dto.leaseId,
      },
    });

    if (!lease) {
      throw new NotFoundException('Lease not found');
    }

    if (dto.amount <= 0) {
      throw new BadRequestException('Invoice amount must be positive');
    }

    return this.prisma.invoice.create({
      data: {
        leaseId: dto.leaseId,
        amount: dto.amount,
        dueDate: new Date(dto.dueDate),
        status: InvoiceStatus.UNPAID,
        paid: false,
      },
    });
  }

  private enrichInvoice(invoice: any) {
    const totalPaid = invoice.payments.reduce(
      (sum: number, payment: any) => sum + payment.amount,
      0,
    );

    const remainingAmount = Math.max(invoice.amount - totalPaid, 0);

    return {
      ...invoice,
      totalPaid,
      remainingAmount,
    };
  }

  private nextDueDate(date: Date, frequency: PaymentFrequency) {
    switch (frequency) {
      case PaymentFrequency.DAILY:
        return addDays(date, 1);

      case PaymentFrequency.WEEKLY:
        return addWeeks(date, 1);

      case PaymentFrequency.MONTHLY:
        return addMonths(date, 1);

      case PaymentFrequency.YEARLY:
        return addYears(date, 1);

      default:
        return addMonths(date, 1);
    }
  }

  private sameOrBefore(a: Date, b: Date) {
    return a.getTime() <= b.getTime();
  }

  async generateDueInvoicesForOrganization(orgId: string) {
    if (!orgId) {
      throw new BadRequestException('No organization attached to your account');
    }

    const now = new Date();

    const leases = await this.prisma.lease.findMany({
      where: {
        organizationId: orgId,
        status: LeaseStatus.ACTIVE,
        startDate: {
          lte: now,
        },
      },
      include: {
        invoices: {
          orderBy: {
            dueDate: 'desc',
          },
        },
      },
    });

    const createdInvoices: any[] = [];

    for (const lease of leases) {
      let nextDate: Date;

      if (lease.invoices.length === 0) {
        nextDate = lease.startDate;
      } else {
        const latestInvoice = lease.invoices[0];
        nextDate = this.nextDueDate(latestInvoice.dueDate, lease.frequency);
      }

      let guard = 0;

      while (
        this.sameOrBefore(nextDate, now) &&
        this.sameOrBefore(nextDate, lease.endDate)
      ) {
        guard++;

        if (guard > 120) {
          throw new BadRequestException(
            `Too many invoices generated for lease ${lease.id}. Please check lease dates.`,
          );
        }

        const existingInvoice = await this.prisma.invoice.findFirst({
          where: {
            leaseId: lease.id,
            dueDate: nextDate,
          },
        });

        if (!existingInvoice) {
          const invoice = await this.prisma.invoice.create({
            data: {
              leaseId: lease.id,
              amount: lease.rentAmount,
              dueDate: nextDate,
              status: InvoiceStatus.UNPAID,
              paid: false,
              metadata: {
                autoGenerated: true,
                frequency: lease.frequency,
                generatedAt: new Date().toISOString(),
              },
            },
          });

          createdInvoices.push(invoice);
        }

        nextDate = this.nextDueDate(nextDate, lease.frequency);
      }
    }

    return {
      success: true,
      createdCount: createdInvoices.length,
      invoices: createdInvoices,
    };
  }

  private async generateDueInvoicesForTenantUser(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: {
        id: userId,
      },
      select: {
        organizationId: true,
      },
    });

    if (!user?.organizationId) {
      return {
        success: false,
        createdCount: 0,
        invoices: [],
      };
    }

    return this.generateDueInvoicesForOrganization(user.organizationId);
  }

  async findAllByOrganization(orgId: string) {
    await this.generateDueInvoicesForOrganization(orgId);

    const invoices = await this.prisma.invoice.findMany({
      where: {
        lease: {
          unit: {
            organizationId: orgId,
          },
        },
      },
      include: {
        payments: true,
        lease: {
          include: {
            tenant: {
              include: {
                user: true,
              },
            },
            unit: {
              include: {
                property: true,
              },
            },
          },
        },
      },
      orderBy: {
        dueDate: 'desc',
      },
    });

    return invoices.map((invoice) => this.enrichInvoice(invoice));
  }

  async findAllByTenant(userId: string) {
    await this.generateDueInvoicesForTenantUser(userId);

    const invoices = await this.prisma.invoice.findMany({
      where: {
        lease: {
          tenant: {
            userId,
          },
        },
      },
      include: {
        payments: true,
        lease: {
          include: {
            tenant: {
              include: {
                user: true,
              },
            },
            unit: {
              include: {
                property: true,
              },
            },
          },
        },
      },
      orderBy: {
        dueDate: 'desc',
      },
    });

    return invoices.map((invoice) => this.enrichInvoice(invoice));
  }

  async findOneForUser(id: string, user: any) {
    if (user.role === 'TENANT') {
      await this.generateDueInvoicesForTenantUser(user.id);
      return this.findOneForTenant(id, user.id);
    }

    await this.generateDueInvoicesForOrganization(user.organizationId);
    return this.findOneForOrganization(id, user.organizationId);
  }

  async findOneForOrganization(id: string, orgId: string) {
    const invoice = await this.prisma.invoice.findFirst({
      where: {
        id,
        lease: {
          unit: {
            organizationId: orgId,
          },
        },
      },
      include: {
        payments: true,
        lease: {
          include: {
            tenant: {
              include: {
                user: true,
              },
            },
            unit: {
              include: {
                property: true,
              },
            },
          },
        },
      },
    });

    if (!invoice) {
      throw new NotFoundException('Invoice not found');
    }

    return this.enrichInvoice(invoice);
  }

  async findOneForTenant(id: string, tenantUserId: string) {
    const invoice = await this.prisma.invoice.findFirst({
      where: {
        id,
        lease: {
          tenant: {
            userId: tenantUserId,
          },
        },
      },
      include: {
        payments: true,
        lease: {
          include: {
            tenant: {
              include: {
                user: true,
              },
            },
            unit: {
              include: {
                property: true,
              },
            },
          },
        },
      },
    });

    if (!invoice) {
      throw new ForbiddenException('You can only access your own invoices');
    }

    return this.enrichInvoice(invoice);
  }
}