// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC95Rtk8J8cpzs0JrPxUINw5xKS_pA37I',
    appId: '1:848757067501:web:157d2b2a3ce646a85c86e4',
    messagingSenderId: '848757067501',
    projectId: 'tunixplore-41763',
    authDomain: 'tunixplore-41763.firebaseapp.com',
    storageBucket: 'tunixplore-41763.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvqCQd0XBYyTHYQrCzKqzVhRqQqdcBvJI',
    appId: '1:848757067501:android:38e8d0cd0c2d20e75c86e4',
    messagingSenderId: '848757067501',
    projectId: 'tunixplore-41763',
    storageBucket: 'tunixplore-41763.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV-fxyg2xf2ylC5q2NY30fJYliegIEN7I',
    appId: '1:848757067501:ios:acfb21e4bfd6f7635c86e4',
    messagingSenderId: '848757067501',
    projectId: 'tunixplore-41763',
    storageBucket: 'tunixplore-41763.firebasestorage.app',
    iosBundleId: 'com.example.tunixplore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV-fxyg2xf2ylC5q2NY30fJYliegIEN7I',
    appId: '1:848757067501:ios:acfb21e4bfd6f7635c86e4',
    messagingSenderId: '848757067501',
    projectId: 'tunixplore-41763',
    storageBucket: 'tunixplore-41763.firebasestorage.app',
    iosBundleId: 'com.example.tunixplore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC95Rtk8J8cpzs0JrPxUINw5xKS_pA37I',
    appId: '1:848757067501:web:637cfd727c69e6bf5c86e4',
    messagingSenderId: '848757067501',
    projectId: 'tunixplore-41763',
    authDomain: 'tunixplore-41763.firebaseapp.com',
    storageBucket: 'tunixplore-41763.firebasestorage.app',
  );
}
