using System;
using System.Collections.Generic;

namespace SR750.Listener
{
    public class LanguageService
    {
        private string _lang = "en";

        public string CurrentLang => _lang;
        public string CurrentLanguage => _lang.ToUpper();

        public event Action? OnLanguageChanged;

        public void Toggle()
        {
            _lang = _lang == "en" ? "de" : "en";
            OnLanguageChanged?.Invoke();
        }

        public void SetLanguage(string lang)
        {
            _lang = lang.ToLower();
            OnLanguageChanged?.Invoke();
        }

        public string T(string key)
        {
            var texts = new Dictionary<string, Dictionary<string, string>>
            {
                ["EN"] = new()
                {
                    ["access_denied"] = "Access denied",
                    ["total_scans"] = "Total Scans",
                    ["ok_rate"] = "OK Rate",
                    ["chart_scans_per_day"] = "Scans per Day",
                    ["chart_duplicates_per_day"] = "Duplicates per Day",
                    ["chart_top_references"] = "Top References by Duplicate",
                    ["chart_scans_by_camera"] = "Scans by Camera",
                    ["chart_green_red"] = "GREEN vs RED",
                    ["section1_text"] = "The DMC Validation System automatically reads and validates DataMatrix codes on cables produced at D-Braun Tunisia. The system connects to Keyence SR-750 cameras via TCP/IP and validates each scan in real-time against project configurations stored in the database.",
                    ["step1"] = "Open XAMPP and start Apache and MySQL",
                    ["step2"] = "Open Terminal 1 — run the Listener:",
                    ["step3"] = "Open Terminal 2 — run the Web Dashboard:",
                    ["step4"] = "Open browser:",
                    ["step5"] = "Login with your credentials (Admin or Supervisor)",
                    ["section3_text"] = "Each cable scan is automatically validated against these rules:",
                    ["green_desc"] = "Known customer prefix, correct length, sequential counter, valid production date",
                    ["red_desc"] = "One or more validation rules failed",
                    ["description"] = "Description",
                    ["reason_unknown"] = "Customer prefix not found in database",
                    ["reason_length"] = "Code length does not match project config",
                    ["reason_duplicate"] = "Same counter already scanned",
                    ["reason_jump"] = "Counter skipped a value (+2 or more)",
                    ["reason_backward"] = "Counter went backwards",
                    ["reason_date"] = "Day value out of range (1-366)",
                    ["reason_overflow"] = "Counter exceeds maximum configured value",
                    ["reason_noread"] = "Camera could not read the code",
                    ["page_dashboard_desc"] = "Real-time overview of all scans. Shows total, GREEN, RED, duplicates and OK rate. Includes live scan history table with filters.",
                    ["page_charts_desc"] = "Analytics charts: scans per day, duplicates trend, top references, scans by camera, GREEN vs RED ratio.",
                    ["page_logs_desc"] = "Full paginated history with advanced filters (date, station, camera, status, reason). Export to CSV. Click View for scan detail with screenshot.",
                    ["page_cameras_desc"] = "Camera management. View connected cameras and their assigned projects.",
                    ["page_projects_desc"] = "Project configuration management. Add or modify customer project rules (length, counter position, date fields).",
                    ["page_users_desc"] = "User management. Add/edit/disable operators and supervisors. Assign roles: Admin or Supervisor.",
                    ["port"] = "Port",
                    ["admin_perm1"] = "Full access to all pages",
                    ["admin_perm2"] = "Manage users, projects, cameras",
                    ["admin_perm3"] = "View all scan history and logs",
                    ["admin_perm4"] = "Export data to CSV",
                    ["sup_perm1"] = "View Charts & AI page only",
                    ["sup_perm2"] = "Monitor GREEN/RED statistics",
                    ["sup_perm3"] = "No configuration access",
                    ["user_management"] = "Users Management",
                    ["add_user"] = "Add User",
                    ["edit_user"] = "Edit User",
                    ["total_users"] = "Total Users",
                    ["admins"] = "Admins",
                    ["supervisors"] = "Supervisors",
                    ["no_users"] = "No users found",
                    ["badge_code"] = "Badge Code",
                    ["you"] = "You",
                    ["badge_rfid"] = "Badge RFID Code",
                    ["badge_placeholder"] = "Scan badge or enter code...",
                    ["enter_username"] = "Enter username",
                    ["enter_password"] = "Enter password",
                    ["password_optional"] = "(leave empty to keep current)",
                    ["password_keep"] = "Leave empty to keep current",
                    ["delete_user_title"] = "Delete User?",
                    ["username_required"] = "Username is required",
                    ["password_required_new"] = "Password is required for new users",
                    ["project_management"] = "Projects Management",
                    ["add_project"] = "Add Project",
                    ["edit_project"] = "Edit Project",
                    ["total_projects"] = "Total Projects",
                    ["no_projects"] = "No projects found",
                    ["customer"] = "Customer",
                    ["label_length"] = "Label Len.",
                    ["counter_max"] = "Counter Max",
                    ["actions"] = "Actions",
                    ["customer_number"] = "Customer Number",
                    ["counter_start"] = "Counter Start",
                    ["counter_length"] = "Counter Length",
                    ["year_start"] = "Year Start",
                    ["day_start"] = "Day Start",
                    ["day_length"] = "Day Length",
                    ["delete_project_title"] = "Delete Project?",
                    ["project_required_fields"] = "Station Name, Customer Number and Prefix are required",
                    ["camera_management"] = "Cameras Management",
                    ["add_camera"] = "Add Camera",
                    ["edit_camera"] = "Edit Camera",
                    ["total_cameras"] = "Total Cameras",
                    ["active"] = "Active",
                    ["inactive"] = "Inactive",
                    ["no_cameras"] = "No cameras found",
                    ["ip_address"] = "IP Address",
                    ["project"] = "Project",
                    ["location"] = "Location",
                    ["added"] = "Added",
                    ["disable"] = "Disable",
                    ["enable"] = "Enable",
                    ["camera_id"] = "Camera ID",
                    ["station_name"] = "Station Name",
                    ["select_project"] = "Select project...",
                    ["save_changes"] = "Save Changes",
                    ["delete_camera_title"] = "Delete Camera?",
                    ["delete_confirm"] = "Delete",
                    ["camera_required_fields"] = "Camera ID, IP Address and Station Name are required",
                    ["export_csv"] = "Export CSV",
                    ["search_dmc"] = "Search DMC Code",
                    ["search_placeholder"] = "Search code...",
                    ["all"] = "All",
                    ["scan_history"] = "Scan History",
                    ["page"] = "Page",
                    ["total"] = "total",
                    ["dmc_code"] = "DMC Code",
                    ["year"] = "Year",
                    ["day"] = "Day",
                    ["detail"] = "Detail",
                    ["prev"] = "Prev",
                    ["next"] = "Next",
                    ["scan_detail"] = "Scan Detail",
                    ["label_capture"] = "Label Capture",
                    ["year_day"] = "Year / Day",
                    ["timestamp"] = "Timestamp",

                    ["dashboard"] = "Dashboard",
                    ["header_subtitle"] = "Real-time monitoring & validation",
                    ["search_filters"] = "Search & Filters",
                    ["date_from"] = "Date from",
                    ["date_to"] = "Date to",
                    ["station"] = "Station",
                    ["camera"] = "Camera",
                    ["status"] = "Status",
                    ["all_stations"] = "All stations",
                    ["all_cameras"] = "All cameras",
                    ["all_status"] = "All status",
                    ["valid"] = "Valid",
                    ["rejected"] = "Rejected",
                    ["apply_filters"] = "Apply filters",
                    ["reset"] = "Reset",
                    ["results"] = "Results",
                    ["duplicates"] = "Duplicates",
                    ["latest_scan"] = "Latest scan",
                    ["code"] = "Code",
                    ["counter"] = "Counter",
                    ["time"] = "Time",
                    ["reason"] = "Reason",
                    ["live_scan_history"] = "Live Scan History",
                    ["no_data"] = "No scans found with current filters",
                    ["charts"] = "Charts & AI",
                    ["charts_ai"] = "Charts & AI",
                    ["logs"] = "Scan Logs",
                    ["scan_logs"] = "Scan Logs",
                    ["cameras"] = "Cameras",
                    ["projects"] = "Projects",
                    ["users"] = "Users",
                    ["guide"] = "Guide",
                    ["logout"] = "Logout",
                    ["guide_title"] = "User Guide",
                    ["guide_subtitle"] = "DMC Validation System — D-Braun Tunisia",
                    ["guide_save_pdf"] = "Save PDF",
                    ["section1_title"] = "System Overview",
                    ["section2_title"] = "Starting the System",
                    ["section3_title"] = "Scan Validation Rules",
                    ["section4_title"] = "Dashboard Pages",
                    ["section5_title"] = "Camera Configuration",
                    ["section6_title"] = "User Roles",
                },

                ["FR"] = new()
                {
                    ["dashboard"] = "Tableau de bord",
                    ["header_subtitle"] = "Surveillance et validation en temps réel",
                    ["search_filters"] = "Recherche et filtres",
                    ["date_from"] = "Date début",
                    ["date_to"] = "Date fin",
                    ["station"] = "Station",
                    ["camera"] = "Caméra",
                    ["status"] = "Statut",
                    ["all_stations"] = "Toutes les stations",
                    ["all_cameras"] = "Toutes les caméras",
                    ["all_status"] = "Tous les statuts",
                    ["valid"] = "Validé",
                    ["rejected"] = "Rejeté",
                    ["apply_filters"] = "Appliquer les filtres",
                    ["reset"] = "Réinitialiser",
                    ["results"] = "Résultats",
                    ["duplicates"] = "Doublons",
                    ["latest_scan"] = "Dernier scan",
                    ["code"] = "Code",
                    ["counter"] = "Compteur",
                    ["time"] = "Heure",
                    ["reason"] = "Raison",
                    ["live_scan_history"] = "Historique des scans",
                    ["no_data"] = "Aucun scan trouvé avec les filtres actuels",
                    ["charts"] = "Graphiques & IA",
                    ["charts_ai"] = "Graphiques & IA",
                    ["logs"] = "Journaux de scan",
                    ["scan_logs"] = "Journaux de scan",
                    ["cameras"] = "Caméras",
                    ["projects"] = "Projets",
                    ["users"] = "Utilisateurs",
                    ["guide"] = "Guide",
                    ["logout"] = "Déconnexion",
                    ["guide_title"] = "Guide utilisateur",
                    ["guide_subtitle"] = "Système de validation DMC — D-Braun Tunisie",
                    ["guide_save_pdf"] = "Enregistrer PDF",
                    ["section1_title"] = "Aperçu du système",
                    ["section2_title"] = "Démarrage du système",
                    ["section3_title"] = "Règles de validation",
                    ["section4_title"] = "Pages du tableau de bord",
                    ["section5_title"] = "Configuration des caméras",
                    ["section6_title"] = "Rôles utilisateurs",
                },

                ["DE"] = new()
                {
                    ["access_denied"] = "Zugriff verweigert",
                    ["total_scans"] = "Scans gesamt",
                    ["ok_rate"] = "OK-Rate",
                    ["chart_scans_per_day"] = "Scans pro Tag",
                    ["chart_duplicates_per_day"] = "Duplikate pro Tag",
                    ["chart_top_references"] = "Top-Referenzen nach Duplikat",
                    ["chart_scans_by_camera"] = "Scans nach Kamera",
                    ["chart_green_red"] = "GRÜN vs ROT",
                    ["section1_text"] = "Das DMC-Validierungssystem liest und validiert automatisch DataMatrix-Codes auf Kabeln, die bei D-Braun Tunesien produziert werden. Das System verbindet sich mit Keyence SR-750 Kameras über TCP/IP und validiert jeden Scan in Echtzeit.",
                    ["step1"] = "XAMPP öffnen und Apache und MySQL starten",
                    ["step2"] = "Terminal 1 öffnen — Listener starten:",
                    ["step3"] = "Terminal 2 öffnen — Web-Dashboard starten:",
                    ["step4"] = "Browser öffnen:",
                    ["step5"] = "Mit Ihren Zugangsdaten anmelden (Admin oder Supervisor)",
                    ["section3_text"] = "Jeder Kabel-Scan wird automatisch gegen diese Regeln validiert:",
                    ["green_desc"] = "Bekanntes Kundenpräfix, korrekte Länge, sequenzieller Zähler, gültiges Produktionsdatum",
                    ["red_desc"] = "Eine oder mehrere Validierungsregeln fehlgeschlagen",
                    ["description"] = "Beschreibung",
                    ["reason_unknown"] = "Kundenpräfix nicht in der Datenbank gefunden",
                    ["reason_length"] = "Code-Länge stimmt nicht mit der Projektkonfiguration überein",
                    ["reason_duplicate"] = "Gleicher Zähler bereits gescannt",
                    ["reason_jump"] = "Zähler hat einen Wert übersprungen (+2 oder mehr)",
                    ["reason_backward"] = "Zähler ist rückwärts gegangen",
                    ["reason_date"] = "Tageswert außerhalb des Bereichs (1-366)",
                    ["reason_overflow"] = "Zähler überschreitet den konfigurierten Maximalwert",
                    ["reason_noread"] = "Kamera konnte den Code nicht lesen",
                    ["page_dashboard_desc"] = "Echtzeit-Übersicht aller Scans. Zeigt Gesamt, GRÜN, ROT, Duplikate und OK-Rate. Enthält Live-Scan-Verlaufstabelle mit Filtern.",
                    ["page_charts_desc"] = "Analysediagramme: Scans pro Tag, Duplikate-Trend, Top-Referenzen, Scans nach Kamera, GRÜN vs ROT-Verhältnis.",
                    ["page_logs_desc"] = "Vollständiger paginierter Verlauf mit erweiterten Filtern. CSV-Export. Klicken Sie auf Ansehen für Scan-Details mit Screenshot.",
                    ["page_cameras_desc"] = "Kameraverwaltung. Verbundene Kameras und ihre zugewiesenen Projekte anzeigen.",
                    ["page_projects_desc"] = "Projektkonfigurationsverwaltung. Kundenregeln hinzufügen oder ändern.",
                    ["page_users_desc"] = "Benutzerverwaltung. Operatoren und Supervisoren hinzufügen/bearbeiten/deaktivieren.",
                    ["port"] = "Port",
                    ["admin_perm1"] = "Vollzugriff auf alle Seiten",
                    ["admin_perm2"] = "Benutzer, Projekte, Kameras verwalten",
                    ["admin_perm3"] = "Gesamten Scan-Verlauf und Protokolle anzeigen",
                    ["admin_perm4"] = "Daten als CSV exportieren",
                    ["sup_perm1"] = "Nur Diagramme & KI-Seite anzeigen",
                    ["sup_perm2"] = "GRÜN/ROT-Statistiken überwachen",
                    ["sup_perm3"] = "Kein Konfigurationszugriff",
                    ["user_management"] = "Benutzerverwaltung",
                    ["add_user"] = "Benutzer hinzufügen",
                    ["edit_user"] = "Benutzer bearbeiten",
                    ["total_users"] = "Benutzer gesamt",
                    ["admins"] = "Admins",
                    ["supervisors"] = "Supervisoren",
                    ["no_users"] = "Keine Benutzer gefunden",
                    ["badge_code"] = "Badge-Code",
                    ["you"] = "Sie",
                    ["badge_rfid"] = "Badge RFID-Code",
                    ["badge_placeholder"] = "Badge scannen oder Code eingeben...",
                    ["enter_username"] = "Benutzername eingeben",
                    ["enter_password"] = "Passwort eingeben",
                    ["password_optional"] = "(leer lassen um beizubehalten)",
                    ["password_keep"] = "Leer lassen um beizubehalten",
                    ["delete_user_title"] = "Benutzer löschen?",
                    ["username_required"] = "Benutzername ist erforderlich",
                    ["password_required_new"] = "Passwort ist für neue Benutzer erforderlich",
                    ["project_management"] = "Projektverwaltung",
                    ["add_project"] = "Projekt hinzufügen",
                    ["edit_project"] = "Projekt bearbeiten",
                    ["total_projects"] = "Projekte gesamt",
                    ["no_projects"] = "Keine Projekte gefunden",
                    ["customer"] = "Kunde",
                    ["label_length"] = "Etik.-Länge",
                    ["counter_max"] = "Zähler Max",
                    ["actions"] = "Aktionen",
                    ["customer_number"] = "Kundennummer",
                    ["counter_start"] = "Zähler Start",
                    ["counter_length"] = "Zählerlänge",
                    ["year_start"] = "Jahr Start",
                    ["day_start"] = "Tag Start",
                    ["day_length"] = "Taglänge",
                    ["delete_project_title"] = "Projekt löschen?",
                    ["project_required_fields"] = "Stationsname, Kundennummer und Präfix sind erforderlich",
                    ["camera_management"] = "Kameraverwaltung",
                    ["add_camera"] = "Kamera hinzufügen",
                    ["edit_camera"] = "Kamera bearbeiten",
                    ["total_cameras"] = "Kameras gesamt",
                    ["active"] = "Aktiv",
                    ["inactive"] = "Inaktiv",
                    ["no_cameras"] = "Keine Kameras gefunden",
                    ["ip_address"] = "IP-Adresse",
                    ["project"] = "Projekt",
                    ["location"] = "Standort",
                    ["added"] = "Hinzugefügt",
                    ["disable"] = "Deaktivieren",
                    ["enable"] = "Aktivieren",
                    ["camera_id"] = "Kamera-ID",
                    ["station_name"] = "Stationsname",
                    ["select_project"] = "Projekt auswählen...",
                    ["save_changes"] = "Änderungen speichern",
                    ["delete_camera_title"] = "Kamera löschen?",
                    ["delete_confirm"] = "Löschen",
                    ["camera_required_fields"] = "Kamera-ID, IP-Adresse und Stationsname sind erforderlich",
                    ["export_csv"] = "CSV exportieren",
                    ["search_dmc"] = "DMC-Code suchen",
                    ["search_placeholder"] = "Code suchen...",
                    ["all"] = "Alle",
                    ["scan_history"] = "Scan-Verlauf",
                    ["page"] = "Seite",
                    ["total"] = "gesamt",
                    ["dmc_code"] = "DMC-Code",
                    ["year"] = "Jahr",
                    ["day"] = "Tag",
                    ["detail"] = "Detail",
                    ["prev"] = "Zurück",
                    ["next"] = "Weiter",
                    ["scan_detail"] = "Scan-Detail",
                    ["label_capture"] = "Etikettenaufnahme",
                    ["year_day"] = "Jahr / Tag",
                    ["timestamp"] = "Zeitstempel",
                    ["dashboard"] = "Dashboard",
                    ["header_subtitle"] = "Echtzeit-Überwachung und Validierung",
                    ["search_filters"] = "Suche und Filter",
                    ["date_from"] = "Datum von",
                    ["date_to"] = "Datum bis",
                    ["station"] = "Station",
                    ["camera"] = "Kamera",
                    ["status"] = "Status",
                    ["all_stations"] = "Alle Stationen",
                    ["all_cameras"] = "Alle Kameras",
                    ["all_status"] = "Alle Status",
                    ["valid"] = "Gültig",
                    ["rejected"] = "Abgelehnt",
                    ["apply_filters"] = "Filter anwenden",
                    ["reset"] = "Zurücksetzen",
                    ["results"] = "Ergebnisse",
                    ["duplicates"] = "Duplikate",
                    ["latest_scan"] = "Letzter Scan",
                    ["code"] = "Code",
                    ["counter"] = "Zähler",
                    ["time"] = "Uhrzeit",
                    ["reason"] = "Grund",
                    ["live_scan_history"] = "Live-Scan-Verlauf",
                    ["no_data"] = "Keine Scans mit den aktuellen Filtern gefunden",
                    ["charts"] = "Diagramme & KI",
                    ["charts_ai"] = "Diagramme & KI",
                    ["logs"] = "Scan-Protokolle",
                    ["scan_logs"] = "Scan-Protokolle",
                    ["cameras"] = "Kameras",
                    ["projects"] = "Projekte",
                    ["users"] = "Benutzer",
                    ["guide"] = "Anleitung",
                    ["logout"] = "Abmelden",
                    ["guide_title"] = "Benutzerhandbuch",
                    ["guide_subtitle"] = "DMC-Validierungssystem — D-Braun Tunesien",
                    ["guide_save_pdf"] = "PDF speichern",
                    ["section1_title"] = "Systemübersicht",
                    ["section2_title"] = "System starten",
                    ["section3_title"] = "Scan-Validierungsregeln",
                    ["section4_title"] = "Dashboard-Seiten",
                    ["section5_title"] = "Kamera-Konfiguration",
                    ["section6_title"] = "Benutzerrollen",
                }
            };

            var langKey = _lang.ToUpper();
            if (texts.ContainsKey(langKey) && texts[langKey].ContainsKey(key))
                return texts[langKey][key];

            return key;
        }
    }
}